/**
 * Mapping des noms de villes vers leurs codes ISO
 */
export const cityToIsoMap: { [key: string]: string } = {
    // France
    'paris': 'FR-75',
    'lyon': 'FR-69',
    'marseille': 'FR-13',
    'toulouse': 'FR-31',
    'nice': 'FR-06',
    'nantes': 'FR-44',
    'strasbourg': 'FR-67',
    'montpellier': 'FR-34',
    'bordeaux': 'FR-33',
    'lille': 'FR-59',

    // Royaume-Uni
    'london': 'GB-LND',
    'manchester': 'GB-MAN',
    'birmingham': 'GB-BIR',
    'glasgow': 'GB-GLG',
    'liverpool': 'GB-LIV',
    'edinburgh': 'GB-EDH',
    'leeds': 'GB-LDS',
    'sheffield': 'GB-SHF',
    'bristol': 'GB-BST',
    'cardiff': 'GB-CRF',

    // États-Unis
    'new york': 'US-NY',
    'los angeles': 'US-CA',
    'chicago': 'US-IL',
    'houston': 'US-TX',
    'miami': 'US-FL',
    'philadelphia': 'US-PA',
    'phoenix': 'US-AZ',
    'san antonio': 'US-TX',
    'san diego': 'US-CA',
    'dallas': 'US-TX',
    'san jose': 'US-CA',
    'austin': 'US-TX',
    'jacksonville': 'US-FL',
    'fort worth': 'US-TX',
    'columbus': 'US-OH',
    'charlotte': 'US-NC',
    'san francisco': 'US-CA',
    'indianapolis': 'US-IN',
    'seattle': 'US-WA',
    'denver': 'US-CO',
    'washington': 'US-DC',
    'boston': 'US-MA',
    'el paso': 'US-TX',
    'detroit': 'US-MI',
    'nashville': 'US-TN',
    'portland': 'US-OR',
    'memphis': 'US-TN',
    'oklahoma city': 'US-OK',
    'las vegas': 'US-NV',
    'louisville': 'US-KY',
    'baltimore': 'US-MD',
    'milwaukee': 'US-WI',
    'albuquerque': 'US-NM',
    'tucson': 'US-AZ',
    'fresno': 'US-CA',
    'sacramento': 'US-CA',
    'kansas city': 'US-MO',
    'mesa': 'US-AZ',
    'atlanta': 'US-GA',
    'omaha': 'US-NE',
    'colorado springs': 'US-CO',
    'raleigh': 'US-NC',
    'virginia beach': 'US-VA',
    'long beach': 'US-CA',
    'miami beach': 'US-FL',
    'minneapolis': 'US-MN',
    'tampa': 'US-FL',
    'new orleans': 'US-LA',
    'cleveland': 'US-OH',
    'honolulu': 'US-HI',

    // Canada
    'toronto': 'CA-ON',
    'vancouver': 'CA-BC',
    'montreal': 'CA-QC',
    'calgary': 'CA-AB',
    'edmonton': 'CA-AB',
    'ottawa': 'CA-ON',
    'winnipeg': 'CA-MB',
    'quebec city': 'CA-QC',
    'hamilton': 'CA-ON',
    'kitchener': 'CA-ON',
    'victoria': 'CA-BC',
    'halifax': 'CA-NS',
    'oshawa': 'CA-ON',
    'windsor': 'CA-ON',
    'saskatoon': 'CA-SK',
    'st. catharines': 'CA-ON',
    'regina': 'CA-SK',
    'sherbrooke': 'CA-QC',
    'kelowna': 'CA-BC',
    'barrie': 'CA-ON',
    'abbotsford': 'CA-BC',
    'kingston': 'CA-ON',
    'sudbury': 'CA-ON',
    'trois-rivières': 'CA-QC',
    'guelph': 'CA-ON',
    'cambridge': 'CA-ON',
    'whitby': 'CA-ON',
    'brantford': 'CA-ON',
    'thunder bay': 'CA-ON',

    // Allemagne
    'berlin': 'DE-BE',
    'munich': 'DE-BY',
    'hamburg': 'DE-HH',
    'cologne': 'DE-NW',
    'frankfurt': 'DE-HE',
    'stuttgart': 'DE-BW',
    'düsseldorf': 'DE-NW',
    'dortmund': 'DE-NW',
    'essen': 'DE-NW',
    'leipzig': 'DE-SN',
    'bremen': 'DE-HB',
    'dresden': 'DE-SN',
    'hanover': 'DE-NI',
    'nuremberg': 'DE-BY',
    'duisburg': 'DE-NW',
    'bochum': 'DE-NW',
    'wuppertal': 'DE-NW',
    'bielefeld': 'DE-NW',
    'bonn': 'DE-NW',
    'münster': 'DE-NW',

    // Espagne
    'madrid': 'ES-MD',
    'barcelona': 'ES-CT',
    'valencia': 'ES-VC',
    'seville': 'ES-AN',
    'zaragoza': 'ES-AR',
    'málaga': 'ES-AN',
    'murcia': 'ES-MC',
    'palma': 'ES-IB',
    'las palmas': 'ES-CN',
    'bilbao': 'ES-PV',
    'alicante': 'ES-VC',
    'córdoba': 'ES-AN',
    'valladolid': 'ES-CL',
    'vigo': 'ES-GA',
    'gijón': 'ES-AS',
    'hospitalet': 'ES-CT',
    'vitoria': 'ES-PV',
    'coruña': 'ES-GA',
    'granada': 'ES-AN',
    'elche': 'ES-VC',

    // Italie
    'rome': 'IT-RM',
    'milan': 'IT-MI',
    'naples': 'IT-NA',
    'turin': 'IT-TO',
    'palermo': 'IT-PA',
    'genoa': 'IT-GE',
    'bologna': 'IT-BO',
    'florence': 'IT-FI',
    'bari': 'IT-BA',
    'catania': 'IT-CT',
    'venice': 'IT-VE',
    'verona': 'IT-VR',
    'messina': 'IT-ME',
    'padua': 'IT-PD',
    'trieste': 'IT-TS',
    'taranto': 'IT-TA',
    'brescia': 'IT-BS',
    'prato': 'IT-PO',
    'parma': 'IT-PR',
    'modena': 'IT-MO',

    // Pays-Bas
    'amsterdam': 'NL-NH',
    'rotterdam': 'NL-ZH',
    'the hague': 'NL-ZH',
    'utrecht': 'NL-UT',
    'eindhoven': 'NL-NB',
    'tilburg': 'NL-NB',
    'groningen': 'NL-GR',
    'almere': 'NL-FL',
    'breda': 'NL-NB',
    'nijmegen': 'NL-GE',

    // Belgique
    'brussels': 'BE-BRU',
    'antwerp': 'BE-VAN',
    'ghent': 'BE-VOV',
    'charleroi': 'BE-WHT',
    'liège': 'BE-WLG',
    'bruges': 'BE-VWV',
    'namur': 'BE-WNA',
    'leuven': 'BE-VBR',
    'mons': 'BE-WHT',
    'aalst': 'BE-VOV',

    // Suisse
    'zurich': 'CH-ZH',
    'geneva': 'CH-GE',
    'basel': 'CH-BS',
    'bern': 'CH-BE',
    'lausanne': 'CH-VD',
    'winterthur': 'CH-ZH',
    'lucerne': 'CH-LU',
    'st. gallen': 'CH-SG',
    'lugano': 'CH-TI',
    'biel': 'CH-BE',

    // Autriche
    'vienna': 'AT-9',
    'graz': 'AT-6',
    'linz': 'AT-4',
    'salzburg': 'AT-5',
    'innsbruck': 'AT-7',
    'klagenfurt': 'AT-2',
    'villach': 'AT-2',
    'wels': 'AT-4',
    'sankt pölten': 'AT-3',
    'dornbirn': 'AT-8',

    // Portugal
    'lisbon': 'PT-11',
    'porto': 'PT-16',
    'vila nova de gaia': 'PT-16',
    'amadora': 'PT-11',
    'braga': 'PT-03',
    'funchal': 'PT-30',
    'coimbra': 'PT-06',
    'setúbal': 'PT-15',
    'almada': 'PT-15',
    'agualva-cacém': 'PT-11',

    // Suède
    'stockholm': 'SE-AB',
    'gothenburg': 'SE-O',
    'malmö': 'SE-M',
    'uppsala': 'SE-C',
    'västerås': 'SE-U',
    'örebro': 'SE-T',
    'linköping': 'SE-E',
    'helsingborg': 'SE-M',
    'jönköping': 'SE-F',
    'norrköping': 'SE-E',

    // Norvège
    'oslo': 'NO-03',
    'bergen': 'NO-46',
    'trondheim': 'NO-50',
    'stavanger': 'NO-11',
    'bærum': 'NO-02',
    'kristiansand': 'NO-10',
    'fredrikstad': 'NO-01',
    'tromsø': 'NO-19',
    'sandnes': 'NO-11',
    'drammen': 'NO-06',

    // Danemark
    'copenhagen': 'DK-84',
    'aarhus': 'DK-82',
    'odense': 'DK-83',
    'aalborg': 'DK-81',
    'esbjerg': 'DK-83',
    'randers': 'DK-82',
    'kolding': 'DK-83',
    'horsens': 'DK-82',
    'vejle': 'DK-83',
    'roskilde': 'DK-84',

    // Finlande
    'helsinki': 'FI-18',
    'espoo': 'FI-18',
    'tampere': 'FI-06',
    'vantaa': 'FI-18',
    'oulu': 'FI-17',
    'turku': 'FI-19',
    'jyväskylä': 'FI-13',
    'lahti': 'FI-16',
    'kuopio': 'FI-08',
    'pori': 'FI-14',

    // Pologne
    'warsaw': 'PL-MZ',
    'krakow': 'PL-MA',
    'łódź': 'PL-LD',
    'wrocław': 'PL-DS',
    'poznań': 'PL-WP',
    'gdańsk': 'PL-PM',
    'szczecin': 'PL-ZP',
    'bydgoszcz': 'PL-KP',
    'lublin': 'PL-LU',
    'katowice': 'PL-SL',

    // République tchèque
    'prague': 'CZ-10',
    'brno': 'CZ-JM',
    'ostrava': 'CZ-MS',
    'plzen': 'CZ-PL',
    'liberec': 'CZ-LI',
    'olomouc': 'CZ-OL',
    'české budějovice': 'CZ-JC',
    'hradec králové': 'CZ-KR',
    'ústí nad labem': 'CZ-US',
    'pardubice': 'CZ-PA',

    // Hongrie
    'budapest': 'HU-BU',
    'debrecen': 'HU-HB',
    'szeged': 'HU-CS',
    'miskolc': 'HU-BZ',
    'pécs': 'HU-BA',
    'győr': 'HU-GS',
    'nyíregyháza': 'HU-SZ',
    'kecskemét': 'HU-BK',
    'székesfehérvár': 'HU-FE',
    'szombathely': 'HU-VA',

    // Roumanie
    'bucharest': 'RO-B',
    'cluj-napoca': 'RO-CJ',
    'timișoara': 'RO-TM',
    'iași': 'RO-IS',
    'constanța': 'RO-CT',
    'craiova': 'RO-DJ',
    'brașov': 'RO-BV',
    'galați': 'RO-GL',
    'ploiești': 'RO-PH',
    'oradea': 'RO-BH',

    // Bulgarie
    'sofia': 'BG-22',
    'plovdiv': 'BG-16',
    'varna': 'BG-03',
    'burgas': 'BG-02',
    'ruse': 'BG-18',
    'stara zagora': 'BG-21',
    'pleven': 'BG-15',
    'sliven': 'BG-19',
    'dobrich': 'BG-08',
    'shumen': 'BG-27',

    // Grèce
    'athens': 'GR-I',
    'thessaloniki': 'GR-B',
    'patras': 'GR-G',
    'piraeus': 'GR-I',
    'larissa': 'GR-E',
    'heraklion': 'GR-M',
    'peristeri': 'GR-I',
    'kallithea': 'GR-I',
    'acharnes': 'GR-I',
    'kalamaria': 'GR-B',

    // Croatie
    'zagreb': 'HR-21',
    'split': 'HR-17',
    'rijeka': 'HR-08',
    'osijek': 'HR-14',
    'zadar': 'HR-13',
    'pula': 'HR-18',
    'slavonski brod': 'HR-12',
    'karlovac': 'HR-04',
    'varaždin': 'HR-05',
    'šibenik': 'HR-15',

    // Serbie
    'belgrade': 'RS-00',
    'novi sad': 'RS-02',
    'niš': 'RS-23',
    'kragujevac': 'RS-25',
    'subotica': 'RS-01',
    'novi pazar': 'RS-20',
    'zrenjanin': 'RS-03',
    'pančevo': 'RS-04',
    'čačak': 'RS-29',
    'novi beograd': 'RS-00',

    // Slovénie
    'ljubljana': 'SI-061',
    'maribor': 'SI-070',
    'celje': 'SI-011',
    'kranj': 'SI-052',
    'velenje': 'SI-133',
    'koper': 'SI-050',
    'novo mesto': 'SI-085',
    'ptuj': 'SI-096',
    'trbovlje': 'SI-129',
    'kamnik': 'SI-043',

    // Slovaquie
    'bratislava': 'SK-BL',
    'košice': 'SK-KI',
    'prešov': 'SK-PV',
    'žilina': 'SK-ZI',
    'banská bystrica': 'SK-BC',
    'nitra': 'SK-NR',
    'trnava': 'SK-TA',
    'trenčín': 'SK-TC',
    'martin': 'SK-ZI',
    'poprad': 'SK-PV',

    // Russie
    'moscow': 'RU-MOW',
    'saint petersburg': 'RU-SPE',
    'novosibirsk': 'RU-NVS',
    'yekaterinburg': 'RU-SVE',
    'nizhny novgorod': 'RU-NIZ',
    'kazan': 'RU-TA',
    'chelyabinsk': 'RU-CHE',
    'omsk': 'RU-OMS',
    'samara': 'RU-SAM',
    'rostov-on-don': 'RU-ROS',
    'ufa': 'RU-BA',
    'krasnoyarsk': 'RU-KYA',
    'perm': 'RU-PER',
    'voronezh': 'RU-VOR',
    'volgograd': 'RU-VGG',
    'krasnodar': 'RU-KDA',
    'saratov': 'RU-SAR',
    'tyumen': 'RU-TYU',
    'tolyatti': 'RU-SAM',
    'izhevsk': 'RU-UD',

    // Ukraine
    'kyiv': 'UA-30',
    'kharkiv': 'UA-63',
    'odesa': 'UA-51',
    'dnipro': 'UA-12',
    'donetsk': 'UA-14',
    'zaporizhzhia': 'UA-23',
    'lviv': 'UA-46',
    'kryvyi rih': 'UA-12',
    'mykolaiv': 'UA-48',
    'mariupol': 'UA-14',

    // Turquie
    'istanbul': 'TR-34',
    'ankara': 'TR-06',
    'izmir': 'TR-35',
    'bursa': 'TR-16',
    'adana': 'TR-01',
    'gaziantep': 'TR-27',
    'konya': 'TR-42',
    'antalya': 'TR-07',
    'kayseri': 'TR-38',
    'mersin': 'TR-33',

    // Japon
    'tokyo': 'JP-13',
    'yokohama': 'JP-14',
    'osaka': 'JP-27',
    'nagoya': 'JP-23',
    'sapporo': 'JP-01',
    'fukuoka': 'JP-40',
    'kobe': 'JP-28',
    'kawasaki': 'JP-14',
    'kyoto': 'JP-26',
    'saitama': 'JP-11',
    'hiroshima': 'JP-34',
    'sendai': 'JP-04',
    'kitakyushu': 'JP-40',
    'chiba': 'JP-12',
    'sakai': 'JP-27',
    'niigata': 'JP-15',
    'hamamatsu': 'JP-22',
    'okayama': 'JP-33',
    'sagamihara': 'JP-14',
    'kumamoto': 'JP-43',

    // Corée du Sud
    'seoul': 'KR-11',
    'busan': 'KR-26',
    'incheon': 'KR-28',
    'daegu': 'KR-27',
    'daejeon': 'KR-30',
    'gwangju': 'KR-29',
    'suwon': 'KR-41',
    'ulsan': 'KR-31',
    'changwon': 'KR-48',
    'goyang': 'KR-41',

    // Chine
    'beijing': 'CN-BJ',
    'shanghai': 'CN-SH',
    'guangzhou': 'CN-GD',
    'shenzhen': 'CN-GD',
    'tianjin': 'CN-TJ',
    'wuhan': 'CN-HB',
    'dongguan': 'CN-GD',
    'chengdu': 'CN-SC',
    'nanjing': 'CN-JS',
    'chongqing': 'CN-CQ',
    'xian': 'CN-SN',
    'shenyang': 'CN-LN',
    'hangzhou': 'CN-ZJ',
    'jinan': 'CN-SD',
    'harbin': 'CN-HL',
    'kunming': 'CN-YN',
    'zhengzhou': 'CN-HA',
    'dalian': 'CN-LN',
    'qingdao': 'CN-SD',
    'changchun': 'CN-JL',

    // Inde
    'mumbai': 'IN-MH',
    'delhi': 'IN-DL',
    'bangalore': 'IN-KA',
    'hyderabad': 'IN-TG',
    'ahmedabad': 'IN-GJ',
    'chennai': 'IN-TN',
    'kolkata': 'IN-WB',
    'surat': 'IN-GJ',
    'pune': 'IN-MH',
    'jaipur': 'IN-RJ',
    'lucknow': 'IN-UP',
    'kanpur': 'IN-UP',
    'nagpur': 'IN-MH',
    'indore': 'IN-MP',
    'thane': 'IN-MH',
    'bhopal': 'IN-MP',
    'visakhapatnam': 'IN-AP',
    'pimpri': 'IN-MH',
    'patna': 'IN-BR',
    'vadodara': 'IN-GJ',

    // Indonésie
    'jakarta': 'ID-JK',
    'surabaya': 'ID-JI',
    'bandung': 'ID-JB',
    'bekasi': 'ID-JB',
    'medan': 'ID-SU',
    'tangerang': 'ID-BT',
    'depok': 'ID-JB',
    'semarang': 'ID-JT',
    'palembang': 'ID-SS',
    'makassar': 'ID-SN',

    // Thaïlande
    'bangkok': 'TH-10',
    'nonthaburi': 'TH-12',
    'nakhon ratchasima': 'TH-30',
    'chiang mai': 'TH-50',
    'hat yai': 'TH-90',
    'udon thani': 'TH-41',
    'pak kret': 'TH-12',
    'khon kaen': 'TH-40',
    'nakhon si thammarat': 'TH-80',
    'chon buri': 'TH-20',

    // Vietnam
    'ho chi minh city': 'VN-SG',
    'hanoi': 'VN-HN',
    'hai phong': 'VN-HP',
    'da nang': 'VN-DN',
    'bien hoa': 'VN-39',
    'hue': 'VN-26',
    'nha trang': 'VN-34',
    'can tho': 'VN-CT',
    'rach gia': 'VN-91',
    'qui nhon': 'VN-31',

    // Philippines
    'manila': 'PH-00',
    'quezon city': 'PH-00',
    'caloocan': 'PH-00',
    'davao': 'PH-11',
    'cebu city': 'PH-07',
    'zamboanga': 'PH-09',
    'antipolo': 'PH-40',
    'pasig': 'PH-00',
    'taguig': 'PH-00',
    'cagayan de oro': 'PH-10',

    // Malaisie
    'kuala lumpur': 'MY-14',
    'george town': 'MY-07',
    'ipoh': 'MY-08',
    'shah alam': 'MY-10',
    'petaling jaya': 'MY-10',
    'johor bahru': 'MY-01',
    'seremban': 'MY-05',
    'kuching': 'MY-13',
    'kota kinabalu': 'MY-12',
    'klang': 'MY-10',

    // Singapour
    'singapore': 'SG-01',

    // Australie
    'sydney': 'AU-NSW',
    'melbourne': 'AU-VIC',
    'brisbane': 'AU-QLD',
    'perth': 'AU-WA',
    'adelaide': 'AU-SA',
    'gold coast': 'AU-QLD',
    'newcastle': 'AU-NSW',
    'canberra': 'AU-ACT',
    'sunshine coast': 'AU-QLD',
    'wollongong': 'AU-NSW',
    'hobart': 'AU-TAS',
    'geelong': 'AU-VIC',
    'townsville': 'AU-QLD',
    'cairns': 'AU-QLD',
    'darwin': 'AU-NT',
    'toowoomba': 'AU-QLD',
    'ballarat': 'AU-VIC',
    'bendigo': 'AU-VIC',
    'albury': 'AU-NSW',
    'launceston': 'AU-TAS',

    // Nouvelle-Zélande
    'auckland': 'NZ-AUK',
    'wellington': 'NZ-WGN',
    'christchurch': 'NZ-CAN',

    'tauranga': 'NZ-BOP',
    'napier': 'NZ-HKB',
    'dunedin': 'NZ-OTA',
    'palmerston north': 'NZ-MWT',
    'nelson': 'NZ-NSN',
    'rotorua': 'NZ-BOP',

    // Brésil
    'são paulo': 'BR-SP',
    'rio de janeiro': 'BR-RJ',
    'brasília': 'BR-DF',
    'salvador': 'BR-BA',
    'fortaleza': 'BR-CE',
    'belo horizonte': 'BR-MG',
    'manaus': 'BR-AM',
    'curitiba': 'BR-PR',
    'recife': 'BR-PE',
    'porto alegre': 'BR-RS',
    'belém': 'BR-PA',
    'goiânia': 'BR-GO',
    'guarulhos': 'BR-SP',
    'campinas': 'BR-SP',
    'são luís': 'BR-MA',
    'são gonçalo': 'BR-RJ',
    'maceió': 'BR-AL',
    'duque de caxias': 'BR-RJ',
    'natal': 'BR-RN',
    'teresina': 'BR-PI',

    // Argentine
    'buenos aires': 'AR-C',

    'rosario': 'AR-S',
    'mendoza': 'AR-M',
    'tucumán': 'AR-T',
    'la plata': 'AR-B',
    'mar del plata': 'AR-B',
    'salta': 'AR-A',
    'santa fe': 'AR-S',
    'san juan': 'AR-J',

    // Chili
    'santiago': 'CL-RM',
    'valparaíso': 'CL-VS',
    'concepción': 'CL-BI',
    'la serena': 'CL-CO',
    'antofagasta': 'CL-AN',
    'temuco': 'CL-AR',
    'rancagua': 'CL-LI',
    'talca': 'CL-ML',
    'arica': 'CL-AP',
    'chillán': 'CL-BI',

    // Colombie
    'bogotá': 'CO-DC',
    'medellín': 'CO-ANT',
    'cali': 'CO-VAC',
    'barranquilla': 'CO-ATL',
    'cartagena': 'CO-BOL',
    'cúcuta': 'CO-NSA',
    'bucaramanga': 'CO-SAN',
    'pereira': 'CO-RIS',
    'santa marta': 'CO-MAG',
    'ibagué': 'CO-TOL',

    // Pérou
    'lima': 'PE-LMA',
    'arequipa': 'PE-ARE',
    'trujillo': 'PE-LAL',
    'chiclayo': 'PE-LAM',
    'piura': 'PE-PIU',
    'iquitos': 'PE-LOR',
    'cusco': 'PE-CUS',
    'chimbote': 'PE-ANC',
    'huancayo': 'PE-JUN',
    'tacna': 'PE-TAC',

    // Venezuela
    'caracas': 'VE-A',
    'maracaibo': 'VE-V',

    'barquisimeto': 'VE-K',
    'maracay': 'VE-D',
    'ciudad guayana': 'VE-C',
    'san cristóbal': 'VE-S',
    'maturín': 'VE-N',
    'ciudad bolívar': 'VE-C',
    'cumana': 'VE-R',

    // Équateur
    'guayaquil': 'EC-G',
    'quito': 'EC-P',
    'cuenca': 'EC-A',
    'santo domingo': 'EC-SD',
    'machala': 'EC-O',
    'durán': 'EC-G',
    'manta': 'EC-M',
    'portoviejo': 'EC-M',
    'ambato': 'EC-T',
    'riobamba': 'EC-H',

    // Uruguay
    'montevideo': 'UY-MO',
    'salto': 'UY-SA',
    'ciudad de la costa': 'UY-CA',
    'paysandú': 'UY-PA',
    'las piedras': 'UY-CA',
    'rivera': 'UY-RV',
    'maldonado': 'UY-MA',
    'tacuarembó': 'UY-TA',
    'melo': 'UY-CE',
    'mercedes': 'UY-SO',

    // Paraguay
    'asunción': 'PY-ASU',
    'ciudad del este': 'PY-10',
    'san lorenzo': 'PY-ASU',
    'luque': 'PY-ASU',
    'capiatá': 'PY-ASU',
    'lambaré': 'PY-ASU',
    'fernando de la mora': 'PY-ASU',
    'limpio': 'PY-ASU',
    'ñemby': 'PY-ASU',
    'encarnación': 'PY-7',

    // Bolivie
    'santa cruz': 'BO-S',
    'la paz': 'BO-L',
    'cochabamba': 'BO-C',
    'sucre': 'BO-H',
    'oruro': 'BO-O',
    'tarija': 'BO-T',
    'potosí': 'BO-P',
    'sacaba': 'BO-C',
    'quillacollo': 'BO-C',
    'trinidad': 'BO-B',

    // Mexique
    'mexico city': 'MX-CMX',
    'guadalajara': 'MX-JAL',
    'monterrey': 'MX-NLE',
    'puebla': 'MX-PUE',
    'tijuana': 'MX-BCN',
    'león': 'MX-GTO',
    'juárez': 'MX-CHH',
    'torreón': 'MX-COA',
    'querétaro': 'MX-QRO',
    'san luis potosí': 'MX-SLP',
    'mérida': 'MX-YUC',
    'mexicali': 'MX-BCN',
    'aguascalientes': 'MX-AGU',
    'cuernavaca': 'MX-MOR',
    'saltillo': 'MX-COA',
    'hermosillo': 'MX-SON',
    'cancún': 'MX-ROO',
    'culiacán': 'MX-SIN',
    'acapulco': 'MX-GRO',
    'tlalnepantla': 'MX-MEX',

    // Afrique du Sud
    'johannesburg': 'ZA-GP',
    'cape town': 'ZA-WC',
    'durban': 'ZA-KZN',
    'pretoria': 'ZA-GP',
    'port elizabeth': 'ZA-EC',
    'pietermaritzburg': 'ZA-KZN',
    'benoni': 'ZA-GP',
    'tembisa': 'ZA-GP',
    'east london': 'ZA-EC',
    'vereeniging': 'ZA-GP',

    // Nigeria
    'lagos': 'NG-LA',
    'kano': 'NG-KN',
    'ibadan': 'NG-OY',
    'abuja': 'NG-FC',
    'port harcourt': 'NG-RI',
    'benin city': 'NG-ED',
    'maiduguri': 'NG-BO',
    'zaria': 'NG-KD',
    'aba': 'NG-AB',
    'jos': 'NG-PL',

    // Kenya
    'nairobi': 'KE-30',
    'mombasa': 'KE-08',
    'nakuru': 'KE-32',
    'eldoret': 'KE-34',
    'kisumu': 'KE-31',
    'thika': 'KE-22',
    'malindi': 'KE-03',
    'kitale': 'KE-26',
    'garissa': 'KE-07',
    'kakamega': 'KE-37',

    // Ghana
    'accra': 'GH-AA',
    'kumasi': 'GH-AH',
    'tamale': 'GH-NP',
    'takoradi': 'GH-WP',
    'cape coast': 'GH-CP',
    'teshi old town': 'GH-AA',
    'tema': 'GH-AA',
    'madina': 'GH-AA',
    'koforidua': 'GH-EP',
    'wa': 'GH-UW',

    // République démocratique du Congo
    'kinshasa': 'CD-KN',
    'lubumbashi': 'CD-HK',
    'mbuji-mayi': 'CD-KE',
    'kisangani': 'CD-TO',
    'masina': 'CD-KN',
    'kananga': 'CD-KS',
    'likasi': 'CD-HK',
    'kolwezi': 'CD-HL',
    'tshikapa': 'CD-KS',
    'bukavu': 'CD-SK',
    'mwene-ditu': 'CD-KE',
    'kikwit': 'CD-KW',
    'mbandaka': 'CD-EQ',
    'matadi': 'CD-BC',
    'uvira': 'CD-SK',
    'butembo': 'CD-NK',
    'gandajika': 'CD-KE',
    'kalemie': 'CD-TG',
    'goma': 'CD-NK',
    'kindu': 'CD-MA',

    // République du Congo
    'brazzaville': 'CG-BZV',
    'pointe-noire': 'CG-16',
    'dolisie': 'CG-12',
    'nkayi': 'CG-12',
    'mossendjo': 'CG-12',
    'ouesso': 'CG-15',
    'madingou': 'CG-12',
    'owando': 'CG-8',
    'impfondo': 'CG-7',
    'sibiti': 'CG-12',

    // Égypte
    'cairo': 'EG-C',
    'alexandria': 'EG-ALX',
    'giza': 'EG-GZ',
    'shubra el kheima': 'EG-KB',
    'port said': 'EG-PTS',
    'suez': 'EG-SUZ',
    'luxor': 'EG-LX',
    'mansoura': 'EG-DK',
    'el mahalla el kubra': 'EG-GH',
    'tanta': 'EG-GH',

    // Maroc
    'casablanca': 'MA-06',
    'rabat': 'MA-07',
    'fès': 'MA-03',
    'marrakech': 'MA-40',
    'agadir': 'MA-83',
    'tangier': 'MA-01',
    'meknès': 'MA-05',
    'oujda': 'MA-02',
    'kenitra': 'MA-07',
    'tetouan': 'MA-01',

    // Algérie
    'algiers': 'DZ-16',
    'oran': 'DZ-31',
    'constantine': 'DZ-25',
    'annaba': 'DZ-23',
    'blida': 'DZ-09',
    'batna': 'DZ-05',
    'djelfa': 'DZ-17',
    'sétif': 'DZ-19',
    'sidi bel abbès': 'DZ-22',
    'biskra': 'DZ-07',

    // Tunisie
    'tunis': 'TN-11',
    'sfax': 'TN-61',
    'sousse': 'TN-51',
    'ettadhamen': 'TN-11',
    'kairouan': 'TN-41',
    'gabès': 'TN-81',
    'bizerte': 'TN-23',
    'ariana': 'TN-12',
    'gafsa': 'TN-71',
    'monastir': 'TN-53',

    // Israël
    'jerusalem': 'IL-JM',
    'tel aviv': 'IL-TA',
    'haifa': 'IL-HA',
    'rishon lezion': 'IL-M',
    'petah tikva': 'IL-M',
    'ashdod': 'IL-D',
    'netanya': 'IL-M',
    'beer sheva': 'IL-D',
    'holon': 'IL-TA',
    'bnei brak': 'IL-TA',

    // Arabie Saoudite
    'riyadh': 'SA-01',
    'jeddah': 'SA-02',
    'mecca': 'SA-02',
    'medina': 'SA-03',
    'dammam': 'SA-04',
    'khobar': 'SA-04',
    'tabuk': 'SA-07',
    'buraidah': 'SA-05',
    'khamis mushait': 'SA-10',
    'hail': 'SA-06',

    // Émirats Arabes Unis
    'dubai': 'AE-DU',
    'abu dhabi': 'AE-AZ',
    'sharjah': 'AE-SH',
    'al ain': 'AE-AZ',
    'ajman': 'AE-AJ',
    'ras al khaimah': 'AE-RK',
    'fujairah': 'AE-FU',
    'umm al quwain': 'AE-UQ',
    'khor fakkan': 'AE-SH',
    'dibba al fujairah': 'AE-FU',

    // Qatar
    'doha': 'QA-DA',
    'al rayyan': 'QA-RA',
    'umm salal': 'QA-MS',
    'al wakrah': 'QA-WA',
    'al khor': 'QA-KH',
    'dukhan': 'QA-RA',
    'mesaieed': 'QA-WA',
    'al shamal': 'QA-SH',
    'al daayen': 'QA-ZA',
    'al shahaniya': 'QA-RA',

    // Koweït
    'kuwait city': 'KW-KU',
    'al ahmadi': 'KW-AH',
    'hawalli': 'KW-HA',
    'as salimiyah': 'KW-HA',
    'sabah as salim': 'KW-MU',
    'al farwaniyah': 'KW-FA',
    'al fahahil': 'KW-AH',
    'ar riqqah': 'KW-MU',
    'al manqaf': 'KW-AH',
    'al jahra': 'KW-JA',

    // Bahreïn
    'manama': 'BH-13',
    'riffa': 'BH-14',
    'muharraq': 'BH-15',
    'hamad town': 'BH-17',
    'a\'ali': 'BH-14',
    'isa town': 'BH-14',
    'sitra': 'BH-14',
    'budaiya': 'BH-17',
    'jidhafs': 'BH-17',
    'al hidd': 'BH-15',

    // Oman
    'muscat': 'OM-MA',
    'seeb': 'OM-MA',
    'salalah': 'OM-ZU',
    'bawshar': 'OM-MA',
    'sohar': 'OM-BN',
    'nizwa': 'OM-DA',
    'sur': 'OM-SS',
    'rustaq': 'OM-BN',
    'barka': 'OM-BN',
    'saham': 'OM-BN',

    // Iran
    'tehran': 'IR-07',
    'mashhad': 'IR-30',
    'isfahan': 'IR-10',
    'karaj': 'IR-23',
    'shiraz': 'IR-14',
    'tabriz': 'IR-01',
    'qom': 'IR-26',
    'ahvaz': 'IR-06',
    'kermanshah': 'IR-05',
    'urmia': 'IR-01',

    // Irak
    'baghdad': 'IQ-BG',
    'basra': 'IQ-BA',
    'mosul': 'IQ-NI',
    'erbil': 'IQ-AR',
    'sulaymaniyah': 'IQ-SU',
    'najaf': 'IQ-NA',
    'karbala': 'IQ-KA',
    'kirkuk': 'IQ-KI',
    'nasiriyah': 'IQ-DH',
    'amarah': 'IQ-MA'
};